//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.6.1055.0.
//
namespace BeanSpitter.Tests.XmlSchemaReaderTests.ClassesFromXsds.Mifid.DraftSchemas.International.Feedback.Statistics
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01", IsNullable=false)]
    public partial class Document {

        private MessageReportHeader2__1[] finInstrmRptgStsAdvcField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StsAdvc", IsNullable=false)]
        public MessageReportHeader2__1[] FinInstrmRptgStsAdvc {
            get {
                return this.finInstrmRptgStsAdvcField;
            }
            set {
                this.finInstrmRptgStsAdvcField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01")]
    public partial class MessageReportHeader2__1 {

        private string msgRptIdrField;

        private StatusAdviceReport1__1 msgStsField;

        private StatusReportRecord2__1[] rcrdStsField;

        /// <remarks/>
        public string MsgRptIdr {
            get {
                return this.msgRptIdrField;
            }
            set {
                this.msgRptIdrField = value;
            }
        }

        /// <remarks/>
        public StatusAdviceReport1__1 MsgSts {
            get {
                return this.msgStsField;
            }
            set {
                this.msgStsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RcrdSts")]
        public StatusReportRecord2__1[] RcrdSts {
            get {
                return this.rcrdStsField;
            }
            set {
                this.rcrdStsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01")]
    public partial class StatusAdviceReport1__1 {

        private FinancialInstrumentReportingStatus1Code__1 rptStsField;

        private GenericValidationRuleIdentification1__1[] vldtnRuleField;

        private OriginalReportStatistics1__1 sttstcsField;

        /// <remarks/>
        public FinancialInstrumentReportingStatus1Code__1 RptSts {
            get {
                return this.rptStsField;
            }
            set {
                this.rptStsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VldtnRule")]
        public GenericValidationRuleIdentification1__1[] VldtnRule {
            get {
                return this.vldtnRuleField;
            }
            set {
                this.vldtnRuleField = value;
            }
        }

        /// <remarks/>
        public OriginalReportStatistics1__1 Sttstcs {
            get {
                return this.sttstcsField;
            }
            set {
                this.sttstcsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01")]
    public enum FinancialInstrumentReportingStatus1Code__1 {

        /// <remarks/>
        CRPT,

        /// <remarks/>
        PART,

        /// <remarks/>
        RMDR,

        /// <remarks/>
        ACPT,

        /// <remarks/>
        RJCT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01")]
    public partial class GenericValidationRuleIdentification1__1 {

        private string idField;

        private string descField;

        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01")]
    public partial class StatusReportRecord2__1 {

        private string orgnlRcrdIdField;

        private FinancialInstrumentReportingStatus3Code__1 stsField;

        private GenericValidationRuleIdentification1__1[] vldtnRuleField;

        /// <remarks/>
        public string OrgnlRcrdId {
            get {
                return this.orgnlRcrdIdField;
            }
            set {
                this.orgnlRcrdIdField = value;
            }
        }

        /// <remarks/>
        public FinancialInstrumentReportingStatus3Code__1 Sts {
            get {
                return this.stsField;
            }
            set {
                this.stsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VldtnRule")]
        public GenericValidationRuleIdentification1__1[] VldtnRule {
            get {
                return this.vldtnRuleField;
            }
            set {
                this.vldtnRuleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01")]
    public enum FinancialInstrumentReportingStatus3Code__1 {

        /// <remarks/>
        ACPT,

        /// <remarks/>
        RJCT,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01")]
    public partial class NumberOfTransactionsPerStatus4__1 {

        private string dtldNbOfTxsField;

        private FinancialInstrumentReportingStatus3Code__1 dtldStsField;

        /// <remarks/>
        public string DtldNbOfTxs {
            get {
                return this.dtldNbOfTxsField;
            }
            set {
                this.dtldNbOfTxsField = value;
            }
        }

        /// <remarks/>
        public FinancialInstrumentReportingStatus3Code__1 DtldSts {
            get {
                return this.dtldStsField;
            }
            set {
                this.dtldStsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT4auth.031.001.01")]
    public partial class OriginalReportStatistics1__1 {

        private string ttlNbOfRcrdsField;

        private NumberOfTransactionsPerStatus4__1[] nbOfRcrdsPerStsField;

        /// <remarks/>
        public string TtlNbOfRcrds {
            get {
                return this.ttlNbOfRcrdsField;
            }
            set {
                this.ttlNbOfRcrdsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfRcrdsPerSts")]
        public NumberOfTransactionsPerStatus4__1[] NbOfRcrdsPerSts {
            get {
                return this.nbOfRcrdsPerStsField;
            }
            set {
                this.nbOfRcrdsPerStsField = value;
            }
        }
    }
}
