//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.6.1055.0.
//
namespace BeanSpitter.Tests.XmlSchemaReaderTests.ClassesFromXsds.Mifid.DraftSchemas.National.Feedback
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01", IsNullable = false)]
    public partial class Document
    {

        private MessageReportHeader3__1[] finInstrmRptgStsAdvcField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StsAdvc", IsNullable = false)]
        public MessageReportHeader3__1[] FinInstrmRptgStsAdvc
        {
            get
            {
                return this.finInstrmRptgStsAdvcField;
            }
            set
            {
                this.finInstrmRptgStsAdvcField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    public partial class MessageReportHeader3__1
    {

        private string msgRptIdrField;

        private StatusAdviceReport2__1 msgStsField;

        private StatusReportRecord2__1[] rcrdStsField;

        /// <remarks/>
        public string MsgRptIdr
        {
            get
            {
                return this.msgRptIdrField;
            }
            set
            {
                this.msgRptIdrField = value;
            }
        }

        /// <remarks/>
        public StatusAdviceReport2__1 MsgSts
        {
            get
            {
                return this.msgStsField;
            }
            set
            {
                this.msgStsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RcrdSts")]
        public StatusReportRecord2__1[] RcrdSts
        {
            get
            {
                return this.rcrdStsField;
            }
            set
            {
                this.rcrdStsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    public partial class StatusAdviceReport2__1
    {

        private FinancialInstrumentReportingStatus1Code rptStsField;

        private GenericValidationRuleIdentification1__1[] vldtnRuleField;

        private OriginalReportStatistics2__1 sttstcsField;

        /// <remarks/>
        public FinancialInstrumentReportingStatus1Code RptSts
        {
            get
            {
                return this.rptStsField;
            }
            set
            {
                this.rptStsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VldtnRule")]
        public GenericValidationRuleIdentification1__1[] VldtnRule
        {
            get
            {
                return this.vldtnRuleField;
            }
            set
            {
                this.vldtnRuleField = value;
            }
        }

        /// <remarks/>
        public OriginalReportStatistics2__1 Sttstcs
        {
            get
            {
                return this.sttstcsField;
            }
            set
            {
                this.sttstcsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    public enum FinancialInstrumentReportingStatus1Code
    {

        /// <remarks/>
        CRPT,

        /// <remarks/>
        INCF,

        /// <remarks/>
        PART,

        /// <remarks/>
        RCVD,

        /// <remarks/>
        RMDR,

        /// <remarks/>
        ACPT,

        /// <remarks/>
        RJCT,

        /// <remarks/>
        WARN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    public partial class GenericValidationRuleIdentification1__1
    {

        private string idField;

        private string descField;

        private ValidationRuleSchemeName1Choice schmeNmField;

        private string issrField;

        /// <remarks/>
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }

        /// <remarks/>
        public ValidationRuleSchemeName1Choice SchmeNm
        {
            get
            {
                return this.schmeNmField;
            }
            set
            {
                this.schmeNmField = value;
            }
        }

        /// <remarks/>
        public string Issr
        {
            get
            {
                return this.issrField;
            }
            set
            {
                this.issrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    public partial class ValidationRuleSchemeName1Choice
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        Cd,

        /// <remarks/>
        Prtry,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    public partial class StatusReportRecord2__1
    {

        private string orgnlRcrdIdField;

        private FinancialInstrumentReportingStatus3Code__1 stsField;

        private GenericValidationRuleIdentification1__1[] vldtnRuleField;

        /// <remarks/>
        public string OrgnlRcrdId
        {
            get
            {
                return this.orgnlRcrdIdField;
            }
            set
            {
                this.orgnlRcrdIdField = value;
            }
        }

        /// <remarks/>
        public FinancialInstrumentReportingStatus3Code__1 Sts
        {
            get
            {
                return this.stsField;
            }
            set
            {
                this.stsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("VldtnRule")]
        public GenericValidationRuleIdentification1__1[] VldtnRule
        {
            get
            {
                return this.vldtnRuleField;
            }
            set
            {
                this.vldtnRuleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    public enum FinancialInstrumentReportingStatus3Code__1
    {

        /// <remarks/>
        PDNG,

        /// <remarks/>
        ACPT,

        /// <remarks/>
        RJCT,

        /// <remarks/>
        RCVD,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    public partial class NumberOfTransactionsPerStatus6__1
    {

        private string dtldNbOfTxsField;

        private FinancialInstrumentReportingStatus3Code__1 dtldStsField;

        /// <remarks/>
        public string DtldNbOfTxs
        {
            get
            {
                return this.dtldNbOfTxsField;
            }
            set
            {
                this.dtldNbOfTxsField = value;
            }
        }

        /// <remarks/>
        public FinancialInstrumentReportingStatus3Code__1 DtldSts
        {
            get
            {
                return this.dtldStsField;
            }
            set
            {
                this.dtldStsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:iso:std:iso:20022:tech:xsd:DRAFT5auth.031.001.01")]
    public partial class OriginalReportStatistics2__1
    {

        private string ttlNbOfRcrdsField;

        private NumberOfTransactionsPerStatus6__1[] nbOfRcrdsPerStsField;

        /// <remarks/>
        public string TtlNbOfRcrds
        {
            get
            {
                return this.ttlNbOfRcrdsField;
            }
            set
            {
                this.ttlNbOfRcrdsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfRcrdsPerSts")]
        public NumberOfTransactionsPerStatus6__1[] NbOfRcrdsPerSts
        {
            get
            {
                return this.nbOfRcrdsPerStsField;
            }
            set
            {
                this.nbOfRcrdsPerStsField = value;
            }
        }
    }
}
