//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.6.1055.0.
//
namespace BeanSpitter.Tests.XmlSchemaReaderTests.ClassesFromXsds.Mifid.International.Feedback.InstrumentStatistics {
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01", IsNullable=false)]
    public partial class Document {

        private TransactionReportingStatistics1[] finInstrmRptgTxRptgSttstcsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TxRptgSttstcs", IsNullable=false)]
        public TransactionReportingStatistics1[] FinInstrmRptgTxRptgSttstcs {
            get {
                return this.finInstrmRptgTxRptgSttstcsField;
            }
            set {
                this.finInstrmRptgTxRptgSttstcsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class TransactionReportingStatistics1 {

        private string sndgAuthrtyField;

        private string mnthField;

        private StatisticsTransactionsReceived1 rcvdFrAgtField;

        private StatisticsTransactionsExchanged1[] sntToAuthrtyField;

        private StatisticsTransactionsExchanged1[] rcvdFrAuthrtyField;

        private SupplementaryData1[] splmtryDataField;

        /// <remarks/>
        public string SndgAuthrty {
            get {
                return this.sndgAuthrtyField;
            }
            set {
                this.sndgAuthrtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="gYearMonth")]
        public string Mnth {
            get {
                return this.mnthField;
            }
            set {
                this.mnthField = value;
            }
        }

        /// <remarks/>
        public StatisticsTransactionsReceived1 RcvdFrAgt {
            get {
                return this.rcvdFrAgtField;
            }
            set {
                this.rcvdFrAgtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SntToAuthrty")]
        public StatisticsTransactionsExchanged1[] SntToAuthrty {
            get {
                return this.sntToAuthrtyField;
            }
            set {
                this.sntToAuthrtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RcvdFrAuthrty")]
        public StatisticsTransactionsExchanged1[] RcvdFrAuthrty {
            get {
                return this.rcvdFrAuthrtyField;
            }
            set {
                this.rcvdFrAuthrtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class StatisticsTransactionsReceived1 {

        private DetailedReportStatistics1 rptSttstcsField;

        private DetailedTransactionStatistics1 newTxSttstcsField;

        private DetailedTransactionStatistics1 cxlSttstcsField;

        /// <remarks/>
        public DetailedReportStatistics1 RptSttstcs {
            get {
                return this.rptSttstcsField;
            }
            set {
                this.rptSttstcsField = value;
            }
        }

        /// <remarks/>
        public DetailedTransactionStatistics1 NewTxSttstcs {
            get {
                return this.newTxSttstcsField;
            }
            set {
                this.newTxSttstcsField = value;
            }
        }

        /// <remarks/>
        public DetailedTransactionStatistics1 CxlSttstcs {
            get {
                return this.cxlSttstcsField;
            }
            set {
                this.cxlSttstcsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class DetailedReportStatistics1 {

        private string ttlNbOfRptsField;

        private NumberOfReportsPerStatus1[] nbOfRptsPerStsField;

        private NumberOfTransactionsPerValidationRule1[] nbOfRptsPerErrField;

        /// <remarks/>
        public string TtlNbOfRpts {
            get {
                return this.ttlNbOfRptsField;
            }
            set {
                this.ttlNbOfRptsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfRptsPerSts")]
        public NumberOfReportsPerStatus1[] NbOfRptsPerSts {
            get {
                return this.nbOfRptsPerStsField;
            }
            set {
                this.nbOfRptsPerStsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfRptsPerErr")]
        public NumberOfTransactionsPerValidationRule1[] NbOfRptsPerErr {
            get {
                return this.nbOfRptsPerErrField;
            }
            set {
                this.nbOfRptsPerErrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class NumberOfReportsPerStatus1 {

        private string dtldNbOfRptsField;

        private FinancialInstrumentReportingStatus1Code dtldStsField;

        /// <remarks/>
        public string DtldNbOfRpts {
            get {
                return this.dtldNbOfRptsField;
            }
            set {
                this.dtldNbOfRptsField = value;
            }
        }

        /// <remarks/>
        public FinancialInstrumentReportingStatus1Code DtldSts {
            get {
                return this.dtldStsField;
            }
            set {
                this.dtldStsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public enum FinancialInstrumentReportingStatus1Code {

        /// <remarks/>
        CRPT,

        /// <remarks/>
        INCF,

        /// <remarks/>
        PART,

        /// <remarks/>
        RCVD,

        /// <remarks/>
        RMDR,

        /// <remarks/>
        ACPT,

        /// <remarks/>
        RJCT,

        /// <remarks/>
        WARN,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class SupplementaryData1 {

        private string plcAndNmField;

        private System.Xml.XmlElement envlpField;

        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class NumberOfTransactionsPerReason2 {

        private string dtldNbOfTxsField;

        private CancelledStatusReason15Code dtldRsnField;

        /// <remarks/>
        public string DtldNbOfTxs {
            get {
                return this.dtldNbOfTxsField;
            }
            set {
                this.dtldNbOfTxsField = value;
            }
        }

        /// <remarks/>
        public CancelledStatusReason15Code DtldRsn {
            get {
                return this.dtldRsnField;
            }
            set {
                this.dtldRsnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public enum CancelledStatusReason15Code {

        /// <remarks/>
        CANI,

        /// <remarks/>
        CSUB,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class DetailedTransactionStatistics3 {

        private string ttlNbOfTxsField;

        private NumberOfTransactionsPerReason2[] nbOfTxsPerRsnField;

        private NumberOfTransactionsPerStatus4[] nbOfTxsPerStsField;

        private NumberOfTransactionsPerValidationRule1[] nbOfTxsPerErrField;

        /// <remarks/>
        public string TtlNbOfTxs {
            get {
                return this.ttlNbOfTxsField;
            }
            set {
                this.ttlNbOfTxsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerRsn")]
        public NumberOfTransactionsPerReason2[] NbOfTxsPerRsn {
            get {
                return this.nbOfTxsPerRsnField;
            }
            set {
                this.nbOfTxsPerRsnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerSts")]
        public NumberOfTransactionsPerStatus4[] NbOfTxsPerSts {
            get {
                return this.nbOfTxsPerStsField;
            }
            set {
                this.nbOfTxsPerStsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerErr")]
        public NumberOfTransactionsPerValidationRule1[] NbOfTxsPerErr {
            get {
                return this.nbOfTxsPerErrField;
            }
            set {
                this.nbOfTxsPerErrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class NumberOfTransactionsPerStatus4 {

        private string dtldNbOfTxsField;

        private FinancialInstrumentReportingStatus3Code dtldStsField;

        /// <remarks/>
        public string DtldNbOfTxs {
            get {
                return this.dtldNbOfTxsField;
            }
            set {
                this.dtldNbOfTxsField = value;
            }
        }

        /// <remarks/>
        public FinancialInstrumentReportingStatus3Code DtldSts {
            get {
                return this.dtldStsField;
            }
            set {
                this.dtldStsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public enum FinancialInstrumentReportingStatus3Code {

        /// <remarks/>
        WARN,

        /// <remarks/>
        RJPD,

        /// <remarks/>
        ACPD,

        /// <remarks/>
        PDNG,

        /// <remarks/>
        ACPT,

        /// <remarks/>
        RJCT,

        /// <remarks/>
        RCVD,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class NumberOfTransactionsPerValidationRule1 {

        private string dtldNbField;

        private GenericValidationRuleIdentification1 dtldVldtnRuleField;

        /// <remarks/>
        public string DtldNb {
            get {
                return this.dtldNbField;
            }
            set {
                this.dtldNbField = value;
            }
        }

        /// <remarks/>
        public GenericValidationRuleIdentification1 DtldVldtnRule {
            get {
                return this.dtldVldtnRuleField;
            }
            set {
                this.dtldVldtnRuleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class GenericValidationRuleIdentification1 {

        private string idField;

        private string descField;

        private ValidationRuleSchemeName1Choice schmeNmField;

        private string issrField;

        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }

        /// <remarks/>
        public ValidationRuleSchemeName1Choice SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }

        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class ValidationRuleSchemeName1Choice {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType {

        /// <remarks/>
        Cd,

        /// <remarks/>
        Prtry,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class NumberOfTransactionsPerReason1 {

        private string dtldNbOfTxsField;

        private AuthorityExchangeReason1Code dtldRsnField;

        /// <remarks/>
        public string DtldNbOfTxs {
            get {
                return this.dtldNbOfTxsField;
            }
            set {
                this.dtldNbOfTxsField = value;
            }
        }

        /// <remarks/>
        public AuthorityExchangeReason1Code DtldRsn {
            get {
                return this.dtldRsnField;
            }
            set {
                this.dtldRsnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public enum AuthorityExchangeReason1Code {

        /// <remarks/>
        CAFI,

        /// <remarks/>
        ADHR,

        /// <remarks/>
        CABC,

        /// <remarks/>
        CABB,

        /// <remarks/>
        CADB,

        /// <remarks/>
        CADU,

        /// <remarks/>
        CAEB,

        /// <remarks/>
        CAIX,

        /// <remarks/>
        CAMB,

        /// <remarks/>
        CASB,

        /// <remarks/>
        CATV,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class DetailedTransactionStatistics2 {

        private string ttlNbOfTxsField;

        private NumberOfTransactionsPerReason1[] nbOfTxsPerRsnField;

        private NumberOfTransactionsPerStatus4[] nbOfTxsPerStsField;

        private NumberOfTransactionsPerValidationRule1[] nbOfTxsPerErrField;

        /// <remarks/>
        public string TtlNbOfTxs {
            get {
                return this.ttlNbOfTxsField;
            }
            set {
                this.ttlNbOfTxsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerRsn")]
        public NumberOfTransactionsPerReason1[] NbOfTxsPerRsn {
            get {
                return this.nbOfTxsPerRsnField;
            }
            set {
                this.nbOfTxsPerRsnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerSts")]
        public NumberOfTransactionsPerStatus4[] NbOfTxsPerSts {
            get {
                return this.nbOfTxsPerStsField;
            }
            set {
                this.nbOfTxsPerStsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerErr")]
        public NumberOfTransactionsPerValidationRule1[] NbOfTxsPerErr {
            get {
                return this.nbOfTxsPerErrField;
            }
            set {
                this.nbOfTxsPerErrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class StatisticsTransactionsExchanged1 {

        private string othrAuthrtyField;

        private DetailedReportStatistics1 rptSttstcsField;

        private DetailedTransactionStatistics2 newTxSttstcsField;

        private DetailedTransactionStatistics3 cxlSttstcsField;

        /// <remarks/>
        public string OthrAuthrty {
            get {
                return this.othrAuthrtyField;
            }
            set {
                this.othrAuthrtyField = value;
            }
        }

        /// <remarks/>
        public DetailedReportStatistics1 RptSttstcs {
            get {
                return this.rptSttstcsField;
            }
            set {
                this.rptSttstcsField = value;
            }
        }

        /// <remarks/>
        public DetailedTransactionStatistics2 NewTxSttstcs {
            get {
                return this.newTxSttstcsField;
            }
            set {
                this.newTxSttstcsField = value;
            }
        }

        /// <remarks/>
        public DetailedTransactionStatistics3 CxlSttstcs {
            get {
                return this.cxlSttstcsField;
            }
            set {
                this.cxlSttstcsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:DRAFT3auth.046.001.01")]
    public partial class DetailedTransactionStatistics1 {

        private string ttlNbOfTxsField;

        private NumberOfTransactionsPerStatus4[] nbOfTxsPerStsField;

        private NumberOfTransactionsPerValidationRule1[] nbOfTxsPerErrField;

        /// <remarks/>
        public string TtlNbOfTxs {
            get {
                return this.ttlNbOfTxsField;
            }
            set {
                this.ttlNbOfTxsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerSts")]
        public NumberOfTransactionsPerStatus4[] NbOfTxsPerSts {
            get {
                return this.nbOfTxsPerStsField;
            }
            set {
                this.nbOfTxsPerStsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NbOfTxsPerErr")]
        public NumberOfTransactionsPerValidationRule1[] NbOfTxsPerErr {
            get {
                return this.nbOfTxsPerErrField;
            }
            set {
                this.nbOfTxsPerErrField = value;
            }
        }
    }
}
