//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace BeanSpitter.Tests.XmlSchemaReaderTests.ClassesFromXsds.Gleif {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016", IsNullable=false)]
    public partial class LEIData {
        
        private LEIHeaderType lEIHeaderField;
        
        private LEIRecordsType lEIRecordsField;
        
        /// <remarks/>
        public LEIHeaderType LEIHeader {
            get {
                return this.lEIHeaderField;
            }
            set {
                this.lEIHeaderField = value;
            }
        }
        
        /// <remarks/>
        public LEIRecordsType LEIRecords {
            get {
                return this.lEIRecordsField;
            }
            set {
                this.lEIRecordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LEIHeaderType {
        
        private System.DateTime contentDateField;
        
        private string originatorField;
        
        private FileContentEnum fileContentField;
        
        private System.DateTime deltaStartField;
        
        private bool deltaStartFieldSpecified;
        
        private string recordCountField;
        
        private HeaderNextVersionType nextVersionField;
        
        private ExtensionType extensionField;
        
        /// <remarks/>
        public System.DateTime ContentDate {
            get {
                return this.contentDateField;
            }
            set {
                this.contentDateField = value;
            }
        }
        
        /// <remarks/>
        public string Originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
            }
        }
        
        /// <remarks/>
        public FileContentEnum FileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DeltaStart {
            get {
                return this.deltaStartField;
            }
            set {
                this.deltaStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeltaStartSpecified {
            get {
                return this.deltaStartFieldSpecified;
            }
            set {
                this.deltaStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string RecordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        public HeaderNextVersionType NextVersion {
            get {
                return this.nextVersionField;
            }
            set {
                this.nextVersionField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum FileContentEnum {
        
        /// <remarks/>
        LOU_FULL_PUBLISHED,
        
        /// <remarks/>
        LOU_DELTA_PUBLISHED,
        
        /// <remarks/>
        GLEIF_FULL_PUBLISHED,
        
        /// <remarks/>
        GLEIF_DELTA_PUBLISHED,
        
        /// <remarks/>
        QUERY_RESPONSE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class HeaderNextVersionType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LEIRecordNextVersionType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class RegistrationNextVersionType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class ValidationAuthorityType {
        
        private string validationAuthorityIDField;
        
        private string otherValidationAuthorityIDField;
        
        private string validationAuthorityEntityIDField;
        
        /// <remarks/>
        public string ValidationAuthorityID {
            get {
                return this.validationAuthorityIDField;
            }
            set {
                this.validationAuthorityIDField = value;
            }
        }
        
        /// <remarks/>
        public string OtherValidationAuthorityID {
            get {
                return this.otherValidationAuthorityIDField;
            }
            set {
                this.otherValidationAuthorityIDField = value;
            }
        }
        
        /// <remarks/>
        public string ValidationAuthorityEntityID {
            get {
                return this.validationAuthorityEntityIDField;
            }
            set {
                this.validationAuthorityEntityIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class RegistrationType {
        
        private System.DateTime initialRegistrationDateField;
        
        private System.DateTime lastUpdateDateField;
        
        private RegistrationStatusEnum registrationStatusField;
        
        private System.DateTime nextRenewalDateField;
        
        private string managingLOUField;
        
        private ValidationSourcesEnum validationSourcesField;
        
        private bool validationSourcesFieldSpecified;
        
        private ValidationAuthorityType validationAuthorityField;
        
        private ValidationAuthorityType[] otherValidationAuthoritiesField;
        
        private RegistrationNextVersionType nextVersionField;
        
        /// <remarks/>
        public System.DateTime InitialRegistrationDate {
            get {
                return this.initialRegistrationDateField;
            }
            set {
                this.initialRegistrationDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdateDate {
            get {
                return this.lastUpdateDateField;
            }
            set {
                this.lastUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        public RegistrationStatusEnum RegistrationStatus {
            get {
                return this.registrationStatusField;
            }
            set {
                this.registrationStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NextRenewalDate {
            get {
                return this.nextRenewalDateField;
            }
            set {
                this.nextRenewalDateField = value;
            }
        }
        
        /// <remarks/>
        public string ManagingLOU {
            get {
                return this.managingLOUField;
            }
            set {
                this.managingLOUField = value;
            }
        }
        
        /// <remarks/>
        public ValidationSourcesEnum ValidationSources {
            get {
                return this.validationSourcesField;
            }
            set {
                this.validationSourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidationSourcesSpecified {
            get {
                return this.validationSourcesFieldSpecified;
            }
            set {
                this.validationSourcesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ValidationAuthorityType ValidationAuthority {
            get {
                return this.validationAuthorityField;
            }
            set {
                this.validationAuthorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OtherValidationAuthority", IsNullable=false)]
        public ValidationAuthorityType[] OtherValidationAuthorities {
            get {
                return this.otherValidationAuthoritiesField;
            }
            set {
                this.otherValidationAuthoritiesField = value;
            }
        }
        
        /// <remarks/>
        public RegistrationNextVersionType NextVersion {
            get {
                return this.nextVersionField;
            }
            set {
                this.nextVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum RegistrationStatusEnum {
        
        /// <remarks/>
        PENDING_VALIDATION,
        
        /// <remarks/>
        ISSUED,
        
        /// <remarks/>
        DUPLICATE,
        
        /// <remarks/>
        LAPSED,
        
        /// <remarks/>
        MERGED,
        
        /// <remarks/>
        RETIRED,
        
        /// <remarks/>
        ANNULLED,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        TRANSFERRED,
        
        /// <remarks/>
        PENDING_TRANSFER,
        
        /// <remarks/>
        PENDING_ARCHIVAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum ValidationSourcesEnum {
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        ENTITY_SUPPLIED_ONLY,
        
        /// <remarks/>
        PARTIALLY_CORROBORATED,
        
        /// <remarks/>
        FULLY_CORROBORATED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class EntityNextVersionType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class SuccessorEntityType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SuccessorEntityName", typeof(NameType))]
        [System.Xml.Serialization.XmlElementAttribute("SuccessorLEI", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherEntityNameType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class NameType {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class OtherEntityNameType : NameType {
        
        private EntityNameTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EntityNameTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum EntityNameTypeEnum {
        
        /// <remarks/>
        ALTERNATIVE_LANGUAGE_LEGAL_NAME,
        
        /// <remarks/>
        PREVIOUS_LEGAL_NAME,
        
        /// <remarks/>
        TRADING_OR_OPERATING_NAME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class AssociatedEntityType {
        
        private object itemField;
        
        private AssociatedEntityTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AssociatedEntityName", typeof(NameType))]
        [System.Xml.Serialization.XmlElementAttribute("AssociatedLEI", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AssociatedEntityTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum AssociatedEntityTypeEnum {
        
        /// <remarks/>
        FUND_FAMILY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LegalFormType {
        
        private string entityLegalFormCodeField;
        
        private string otherLegalFormField;
        
        /// <remarks/>
        public string EntityLegalFormCode {
            get {
                return this.entityLegalFormCodeField;
            }
            set {
                this.entityLegalFormCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OtherLegalForm {
            get {
                return this.otherLegalFormField;
            }
            set {
                this.otherLegalFormField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class RegistrationAuthorityType {
        
        private string registrationAuthorityIDField;
        
        private string otherRegistrationAuthorityIDField;
        
        private string registrationAuthorityEntityIDField;
        
        /// <remarks/>
        public string RegistrationAuthorityID {
            get {
                return this.registrationAuthorityIDField;
            }
            set {
                this.registrationAuthorityIDField = value;
            }
        }
        
        /// <remarks/>
        public string OtherRegistrationAuthorityID {
            get {
                return this.otherRegistrationAuthorityIDField;
            }
            set {
                this.otherRegistrationAuthorityIDField = value;
            }
        }
        
        /// <remarks/>
        public string RegistrationAuthorityEntityID {
            get {
                return this.registrationAuthorityEntityIDField;
            }
            set {
                this.registrationAuthorityEntityIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransliteratedOtherAddressType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class TransliteratedAddressType {
        
        private string firstAddressLineField;
        
        private string addressNumberField;
        
        private string addressNumberWithinBuildingField;
        
        private string mailRoutingField;
        
        private string[] additionalAddressLineField;
        
        private string cityField;
        
        private string regionField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private string langField;
        
        /// <remarks/>
        public string FirstAddressLine {
            get {
                return this.firstAddressLineField;
            }
            set {
                this.firstAddressLineField = value;
            }
        }
        
        /// <remarks/>
        public string AddressNumber {
            get {
                return this.addressNumberField;
            }
            set {
                this.addressNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AddressNumberWithinBuilding {
            get {
                return this.addressNumberWithinBuildingField;
            }
            set {
                this.addressNumberWithinBuildingField = value;
            }
        }
        
        /// <remarks/>
        public string MailRouting {
            get {
                return this.mailRoutingField;
            }
            set {
                this.mailRoutingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalAddressLine")]
        public string[] AdditionalAddressLine {
            get {
                return this.additionalAddressLineField;
            }
            set {
                this.additionalAddressLineField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class TransliteratedOtherAddressType : TransliteratedAddressType {
        
        private TransliteratedAddressTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransliteratedAddressTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum TransliteratedAddressTypeEnum {
        
        /// <remarks/>
        AUTO_ASCII_TRANSLITERATED_LEGAL_ADDRESS,
        
        /// <remarks/>
        AUTO_ASCII_TRANSLITERATED_HEADQUARTERS_ADDRESS,
        
        /// <remarks/>
        PREFERRED_ASCII_TRANSLITERATED_LEGAL_ADDRESS,
        
        /// <remarks/>
        PREFERRED_ASCII_TRANSLITERATED_HEADQUARTERS_ADDRESS,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherAddressType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class AddressType {
        
        private string firstAddressLineField;
        
        private string addressNumberField;
        
        private string addressNumberWithinBuildingField;
        
        private string mailRoutingField;
        
        private string[] additionalAddressLineField;
        
        private string cityField;
        
        private string regionField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private string langField;
        
        /// <remarks/>
        public string FirstAddressLine {
            get {
                return this.firstAddressLineField;
            }
            set {
                this.firstAddressLineField = value;
            }
        }
        
        /// <remarks/>
        public string AddressNumber {
            get {
                return this.addressNumberField;
            }
            set {
                this.addressNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AddressNumberWithinBuilding {
            get {
                return this.addressNumberWithinBuildingField;
            }
            set {
                this.addressNumberWithinBuildingField = value;
            }
        }
        
        /// <remarks/>
        public string MailRouting {
            get {
                return this.mailRoutingField;
            }
            set {
                this.mailRoutingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalAddressLine")]
        public string[] AdditionalAddressLine {
            get {
                return this.additionalAddressLineField;
            }
            set {
                this.additionalAddressLineField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class OtherAddressType : AddressType {
        
        private AddressTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AddressTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum AddressTypeEnum {
        
        /// <remarks/>
        ALTERNATIVE_LANGUAGE_LEGAL_ADDRESS,
        
        /// <remarks/>
        ALTERNATIVE_LANGUAGE_HEADQUARTERS_ADDRESS,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransliteratedOtherEntityNameType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class TransliteratedNameType {
        
        private string langField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class TransliteratedOtherEntityNameType : TransliteratedNameType {
        
        private TransliteratedEntityNameTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TransliteratedEntityNameTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum TransliteratedEntityNameTypeEnum {
        
        /// <remarks/>
        PREFERRED_ASCII_TRANSLITERATED_LEGAL_NAME,
        
        /// <remarks/>
        AUTO_ASCII_TRANSLITERATED_LEGAL_NAME,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class EntityType {
        
        private NameType legalNameField;
        
        private OtherEntityNameType[] otherEntityNamesField;
        
        private TransliteratedOtherEntityNameType[] transliteratedOtherEntityNamesField;
        
        private AddressType legalAddressField;
        
        private AddressType headquartersAddressField;
        
        private OtherAddressType[] otherAddressesField;
        
        private TransliteratedOtherAddressType[] transliteratedOtherAddressesField;
        
        private RegistrationAuthorityType registrationAuthorityField;
        
        private string legalJurisdictionField;
        
        private EntityCategoryTypeEnum entityCategoryField;
        
        private bool entityCategoryFieldSpecified;
        
        private LegalFormType legalFormField;
        
        private AssociatedEntityType associatedEntityField;
        
        private EntityStatusEnum entityStatusField;
        
        private System.DateTime entityExpirationDateField;
        
        private bool entityExpirationDateFieldSpecified;
        
        private EntityExpirationReasonEnum entityExpirationReasonField;
        
        private bool entityExpirationReasonFieldSpecified;
        
        private SuccessorEntityType successorEntityField;
        
        private EntityNextVersionType nextVersionField;
        
        /// <remarks/>
        public NameType LegalName {
            get {
                return this.legalNameField;
            }
            set {
                this.legalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OtherEntityName", IsNullable=false)]
        public OtherEntityNameType[] OtherEntityNames {
            get {
                return this.otherEntityNamesField;
            }
            set {
                this.otherEntityNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TransliteratedOtherEntityName", IsNullable=false)]
        public TransliteratedOtherEntityNameType[] TransliteratedOtherEntityNames {
            get {
                return this.transliteratedOtherEntityNamesField;
            }
            set {
                this.transliteratedOtherEntityNamesField = value;
            }
        }
        
        /// <remarks/>
        public AddressType LegalAddress {
            get {
                return this.legalAddressField;
            }
            set {
                this.legalAddressField = value;
            }
        }
        
        /// <remarks/>
        public AddressType HeadquartersAddress {
            get {
                return this.headquartersAddressField;
            }
            set {
                this.headquartersAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("OtherAddress", IsNullable=false)]
        public OtherAddressType[] OtherAddresses {
            get {
                return this.otherAddressesField;
            }
            set {
                this.otherAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TransliteratedOtherAddress", IsNullable=false)]
        public TransliteratedOtherAddressType[] TransliteratedOtherAddresses {
            get {
                return this.transliteratedOtherAddressesField;
            }
            set {
                this.transliteratedOtherAddressesField = value;
            }
        }
        
        /// <remarks/>
        public RegistrationAuthorityType RegistrationAuthority {
            get {
                return this.registrationAuthorityField;
            }
            set {
                this.registrationAuthorityField = value;
            }
        }
        
        /// <remarks/>
        public string LegalJurisdiction {
            get {
                return this.legalJurisdictionField;
            }
            set {
                this.legalJurisdictionField = value;
            }
        }
        
        /// <remarks/>
        public EntityCategoryTypeEnum EntityCategory {
            get {
                return this.entityCategoryField;
            }
            set {
                this.entityCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityCategorySpecified {
            get {
                return this.entityCategoryFieldSpecified;
            }
            set {
                this.entityCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public LegalFormType LegalForm {
            get {
                return this.legalFormField;
            }
            set {
                this.legalFormField = value;
            }
        }
        
        /// <remarks/>
        public AssociatedEntityType AssociatedEntity {
            get {
                return this.associatedEntityField;
            }
            set {
                this.associatedEntityField = value;
            }
        }
        
        /// <remarks/>
        public EntityStatusEnum EntityStatus {
            get {
                return this.entityStatusField;
            }
            set {
                this.entityStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EntityExpirationDate {
            get {
                return this.entityExpirationDateField;
            }
            set {
                this.entityExpirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityExpirationDateSpecified {
            get {
                return this.entityExpirationDateFieldSpecified;
            }
            set {
                this.entityExpirationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public EntityExpirationReasonEnum EntityExpirationReason {
            get {
                return this.entityExpirationReasonField;
            }
            set {
                this.entityExpirationReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntityExpirationReasonSpecified {
            get {
                return this.entityExpirationReasonFieldSpecified;
            }
            set {
                this.entityExpirationReasonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public SuccessorEntityType SuccessorEntity {
            get {
                return this.successorEntityField;
            }
            set {
                this.successorEntityField = value;
            }
        }
        
        /// <remarks/>
        public EntityNextVersionType NextVersion {
            get {
                return this.nextVersionField;
            }
            set {
                this.nextVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum EntityCategoryTypeEnum {
        
        /// <remarks/>
        BRANCH,
        
        /// <remarks/>
        FUND,
        
        /// <remarks/>
        SOLE_PROPRIETOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum EntityStatusEnum {
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        INACTIVE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public enum EntityExpirationReasonEnum {
        
        /// <remarks/>
        DISSOLVED,
        
        /// <remarks/>
        CORPORATE_ACTION,
        
        /// <remarks/>
        OTHER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LEIRecordType {
        
        private string lEIField;
        
        private EntityType entityField;
        
        private RegistrationType registrationField;
        
        private LEIRecordNextVersionType nextVersionField;
        
        private ExtensionType extensionField;
        
        /// <remarks/>
        public string LEI {
            get {
                return this.lEIField;
            }
            set {
                this.lEIField = value;
            }
        }
        
        /// <remarks/>
        public EntityType Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public RegistrationType Registration {
            get {
                return this.registrationField;
            }
            set {
                this.registrationField = value;
            }
        }
        
        /// <remarks/>
        public LEIRecordNextVersionType NextVersion {
            get {
                return this.nextVersionField;
            }
            set {
                this.nextVersionField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class ExtensionType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gleif.org/data/schema/leidata/2016")]
    public partial class LEIRecordsType {
        
        private LEIRecordType[] lEIRecordField;
        
        private ExtensionType extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LEIRecord")]
        public LEIRecordType[] LEIRecord {
            get {
                return this.lEIRecordField;
            }
            set {
                this.lEIRecordField = value;
            }
        }
        
        /// <remarks/>
        public ExtensionType Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
}
