//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.6.1055.0.
//
namespace BeanSpitter.Tests.XmlSchemaReaderTests.ClassesFromXsds.Mifid.International.Reporting {
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01", IsNullable=false)]
    public partial class Document {

        private ReportingTransactionType1Choice__1[] finInstrmRptgTxRptField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tx", IsNullable=false)]
        public ReportingTransactionType1Choice__1[] FinInstrmRptgTxRpt {
            get {
                return this.finInstrmRptgTxRptField;
            }
            set {
                this.finInstrmRptgTxRptField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class ReportingTransactionType1Choice__1 {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cxl", typeof(SecuritiesTransactionReport2__1))]
        [System.Xml.Serialization.XmlElementAttribute("New", typeof(SecuritiesTransactionReport4__1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransactionReport2__1 {

        private string txIdField;

        private string exctgPtyField;

        private string submitgPtyField;

        private RecordTechnicalData2__1 techAttrbtsField;

        /// <remarks/>
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
            }
        }

        /// <remarks/>
        public string ExctgPty {
            get {
                return this.exctgPtyField;
            }
            set {
                this.exctgPtyField = value;
            }
        }

        /// <remarks/>
        public string SubmitgPty {
            get {
                return this.submitgPtyField;
            }
            set {
                this.submitgPtyField = value;
            }
        }

        /// <remarks/>
        public RecordTechnicalData2__1 TechAttrbts {
            get {
                return this.techAttrbtsField;
            }
            set {
                this.techAttrbtsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class RecordTechnicalData2__1 {

        private System.DateTime rctDtTmField;

        private CancelledStatusReason15Code cxlRsnField;

        /// <remarks/>
        public System.DateTime RctDtTm {
            get {
                return this.rctDtTmField;
            }
            set {
                this.rctDtTmField = value;
            }
        }

        /// <remarks/>
        public CancelledStatusReason15Code CxlRsn {
            get {
                return this.cxlRsnField;
            }
            set {
                this.cxlRsnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum CancelledStatusReason15Code {

        /// <remarks/>
        CANI,

        /// <remarks/>
        CSUB,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class RecordTechnicalData1__1 {

        private System.DateTime rctDtTmField;

        private AuthorityExchangeReason1Code[] xchgRsnField;

        /// <remarks/>
        public System.DateTime RctDtTm {
            get {
                return this.rctDtTmField;
            }
            set {
                this.rctDtTmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XchgRsn")]
        public AuthorityExchangeReason1Code[] XchgRsn {
            get {
                return this.xchgRsnField;
            }
            set {
                this.xchgRsnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum AuthorityExchangeReason1Code {

        /// <remarks/>
        CAFI,

        /// <remarks/>
        ADHR,

        /// <remarks/>
        CABC,

        /// <remarks/>
        CABB,

        /// <remarks/>
        CADB,

        /// <remarks/>
        CADU,

        /// <remarks/>
        CAEB,

        /// <remarks/>
        CAIX,

        /// <remarks/>
        CAMB,

        /// <remarks/>
        CASB,

        /// <remarks/>
        CATV,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransactionIndicator2__1 {

        private ReportingWaiverType1Code[] wvrIndField;

        private Side5Code shrtSellgIndField;

        private bool shrtSellgIndFieldSpecified;

        private ReportingWaiverType3Code[] oTCPstTradIndField;

        private bool rskRdcgTxField;

        private bool rskRdcgTxFieldSpecified;

        private bool sctiesFincgTxIndField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WvrInd")]
        public ReportingWaiverType1Code[] WvrInd {
            get {
                return this.wvrIndField;
            }
            set {
                this.wvrIndField = value;
            }
        }

        /// <remarks/>
        public Side5Code ShrtSellgInd {
            get {
                return this.shrtSellgIndField;
            }
            set {
                this.shrtSellgIndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShrtSellgIndSpecified {
            get {
                return this.shrtSellgIndFieldSpecified;
            }
            set {
                this.shrtSellgIndFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OTCPstTradInd")]
        public ReportingWaiverType3Code[] OTCPstTradInd {
            get {
                return this.oTCPstTradIndField;
            }
            set {
                this.oTCPstTradIndField = value;
            }
        }

        /// <remarks/>
        public bool RskRdcgTx {
            get {
                return this.rskRdcgTxField;
            }
            set {
                this.rskRdcgTxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RskRdcgTxSpecified {
            get {
                return this.rskRdcgTxFieldSpecified;
            }
            set {
                this.rskRdcgTxFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool SctiesFincgTxInd {
            get {
                return this.sctiesFincgTxIndField;
            }
            set {
                this.sctiesFincgTxIndField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum ReportingWaiverType1Code {

        /// <remarks/>
        OILQ,

        /// <remarks/>
        NLIQ,

        /// <remarks/>
        PRIC,

        /// <remarks/>
        ILQD,

        /// <remarks/>
        RFPT,

        /// <remarks/>
        SIZE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum Side5Code {

        /// <remarks/>
        SESH,

        /// <remarks/>
        SELL,

        /// <remarks/>
        SSEX,

        /// <remarks/>
        UNDI,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum ReportingWaiverType3Code {

        /// <remarks/>
        BENC,

        /// <remarks/>
        ACTX,

        /// <remarks/>
        ILQD,

        /// <remarks/>
        SIZE,

        /// <remarks/>
        CANC,

        /// <remarks/>
        AMND,

        /// <remarks/>
        SDIV,

        /// <remarks/>
        RPRI,

        /// <remarks/>
        DUPL,

        /// <remarks/>
        LRGS,

        /// <remarks/>
        TNCP,

        /// <remarks/>
        TPAC,

        /// <remarks/>
        XFPH,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class ExecutingParty1Choice__1 {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Algo", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Clnt", typeof(NoReasonCode))]
        [System.Xml.Serialization.XmlElementAttribute("Prsn", typeof(PersonIdentification12__1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum NoReasonCode {

        /// <remarks/>
        NORE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class PersonIdentification12__1 {

        private string ctryOfBrnchField;

        private GenericPersonIdentification1__1 othrField;

        /// <remarks/>
        public string CtryOfBrnch {
            get {
                return this.ctryOfBrnchField;
            }
            set {
                this.ctryOfBrnchField = value;
            }
        }

        /// <remarks/>
        public GenericPersonIdentification1__1 Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class GenericPersonIdentification1__1 {

        private string idField;

        private PersonIdentificationSchemeName1Choice__1 schmeNmField;

        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        public PersonIdentificationSchemeName1Choice__1 SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class PersonIdentificationSchemeName1Choice__1 {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType {

        /// <remarks/>
        Cd,

        /// <remarks/>
        Prtry,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class InvestmentParty1Choice__1 {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Algo", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prsn", typeof(PersonIdentification12__1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class DerivativeForeignExchange2 {

        private string othrNtnlCcyField;

        /// <remarks/>
        public string OthrNtnlCcy {
            get {
                return this.othrNtnlCcyField;
            }
            set {
                this.othrNtnlCcyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class DerivativeInterest2 {

        private string othrNtnlCcyField;

        /// <remarks/>
        public string OthrNtnlCcy {
            get {
                return this.othrNtnlCcyField;
            }
            set {
                this.othrNtnlCcyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class AssetClassAttributes1Choice__1 {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FX", typeof(DerivativeForeignExchange2))]
        [System.Xml.Serialization.XmlElementAttribute("Intrst", typeof(DerivativeInterest2))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransactionPrice1__1 {

        private PriceStatus1Code__1 pdgField;

        private string ccyField;

        /// <remarks/>
        public PriceStatus1Code__1 Pdg {
            get {
                return this.pdgField;
            }
            set {
                this.pdgField = value;
            }
        }

        /// <remarks/>
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum PriceStatus1Code__1 {

        /// <remarks/>
        PNDG,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransactionPrice4Choice__1 {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoPric", typeof(SecuritiesTransactionPrice1__1))]
        [System.Xml.Serialization.XmlElementAttribute("Pric", typeof(SecuritiesTransactionPrice2Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransactionPrice2Choice {

        private object itemField;

        private ItemChoiceType3 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BsisPts", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("MntryVal", typeof(AmountAndDirection61))]
        [System.Xml.Serialization.XmlElementAttribute("Pctg", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("Yld", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class AmountAndDirection61 {

        private ActiveCurrencyAnd13DecimalAmount amtField;

        private bool sgnField;

        private bool sgnFieldSpecified;

        /// <remarks/>
        public ActiveCurrencyAnd13DecimalAmount Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }

        /// <remarks/>
        public bool Sgn {
            get {
                return this.sgnField;
            }
            set {
                this.sgnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SgnSpecified {
            get {
                return this.sgnFieldSpecified;
            }
            set {
                this.sgnFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class ActiveCurrencyAnd13DecimalAmount {

        private string ccyField;

        private decimal valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType3 {

        /// <remarks/>
        BsisPts,

        /// <remarks/>
        MntryVal,

        /// <remarks/>
        Pctg,

        /// <remarks/>
        Yld,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class BasketDescription3 {

        private string[] iSINField;

        private FinancialInstrument58[] indxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ISIN")]
        public string[] ISIN {
            get {
                return this.iSINField;
            }
            set {
                this.iSINField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Indx")]
        public FinancialInstrument58[] Indx {
            get {
                return this.indxField;
            }
            set {
                this.indxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class FinancialInstrument58 {

        private string iSINField;

        private FloatingInterestRate8 nmField;

        /// <remarks/>
        public string ISIN {
            get {
                return this.iSINField;
            }
            set {
                this.iSINField = value;
            }
        }

        /// <remarks/>
        public FloatingInterestRate8 Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class FloatingInterestRate8 {

        private BenchmarkCurveName5Choice refRateField;

        private InterestRateContractTerm2 termField;

        /// <remarks/>
        public BenchmarkCurveName5Choice RefRate {
            get {
                return this.refRateField;
            }
            set {
                this.refRateField = value;
            }
        }

        /// <remarks/>
        public InterestRateContractTerm2 Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class BenchmarkCurveName5Choice {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Indx", typeof(BenchmarkCurveName2Code))]
        [System.Xml.Serialization.XmlElementAttribute("Nm", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum BenchmarkCurveName2Code {

        /// <remarks/>
        WIBO,

        /// <remarks/>
        TREA,

        /// <remarks/>
        TIBO,

        /// <remarks/>
        TLBO,

        /// <remarks/>
        SWAP,

        /// <remarks/>
        STBO,

        /// <remarks/>
        PRBO,

        /// <remarks/>
        PFAN,

        /// <remarks/>
        NIBO,

        /// <remarks/>
        MAAA,

        /// <remarks/>
        MOSP,

        /// <remarks/>
        LIBO,

        /// <remarks/>
        LIBI,

        /// <remarks/>
        JIBA,

        /// <remarks/>
        ISDA,

        /// <remarks/>
        GCFR,

        /// <remarks/>
        FUSW,

        /// <remarks/>
        EUCH,

        /// <remarks/>
        EUUS,

        /// <remarks/>
        EURI,

        /// <remarks/>
        EONS,

        /// <remarks/>
        EONA,

        /// <remarks/>
        CIBO,

        /// <remarks/>
        CDOR,

        /// <remarks/>
        BUBO,

        /// <remarks/>
        BBSW,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class InterestRateContractTerm2 {

        private RateBasis1Code unitField;

        private decimal valField;

        /// <remarks/>
        public RateBasis1Code Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }

        /// <remarks/>
        public decimal Val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum RateBasis1Code {

        /// <remarks/>
        DAYS,

        /// <remarks/>
        MNTH,

        /// <remarks/>
        WEEK,

        /// <remarks/>
        YEAR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class FinancialInstrumentIdentification6Choice {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ISIN", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Indx", typeof(FinancialInstrument58))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class FinancialInstrumentIdentification7Choice {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bskt", typeof(BasketDescription3))]
        [System.Xml.Serialization.XmlElementAttribute("Sngl", typeof(FinancialInstrumentIdentification6Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SwapLegIdentification2__1 {

        private FinancialInstrumentIdentification7Choice swpInField;

        private FinancialInstrumentIdentification7Choice swpOutField;

        /// <remarks/>
        public FinancialInstrumentIdentification7Choice SwpIn {
            get {
                return this.swpInField;
            }
            set {
                this.swpInField = value;
            }
        }

        /// <remarks/>
        public FinancialInstrumentIdentification7Choice SwpOut {
            get {
                return this.swpOutField;
            }
            set {
                this.swpOutField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class UnderlyingIdentification2Choice__1 {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(FinancialInstrumentIdentification7Choice))]
        [System.Xml.Serialization.XmlElementAttribute("Swp", typeof(SwapLegIdentification2__1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class DerivativeInstrument6__1 {

        private System.DateTime xpryDtField;

        private bool xpryDtFieldSpecified;

        private decimal pricMltplrField;

        private UnderlyingIdentification2Choice__1 undrlygInstrmField;

        private OptionType2Code optnTpField;

        private bool optnTpFieldSpecified;

        private SecuritiesTransactionPrice4Choice__1 strkPricField;

        private OptionStyle7Code optnExrcStyleField;

        private bool optnExrcStyleFieldSpecified;

        private PhysicalTransferType4Code dlvryTpField;

        private AssetClassAttributes1Choice__1 asstClssSpcfcAttrbtsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime XpryDt {
            get {
                return this.xpryDtField;
            }
            set {
                this.xpryDtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XpryDtSpecified {
            get {
                return this.xpryDtFieldSpecified;
            }
            set {
                this.xpryDtFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal PricMltplr {
            get {
                return this.pricMltplrField;
            }
            set {
                this.pricMltplrField = value;
            }
        }

        /// <remarks/>
        public UnderlyingIdentification2Choice__1 UndrlygInstrm {
            get {
                return this.undrlygInstrmField;
            }
            set {
                this.undrlygInstrmField = value;
            }
        }

        /// <remarks/>
        public OptionType2Code OptnTp {
            get {
                return this.optnTpField;
            }
            set {
                this.optnTpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptnTpSpecified {
            get {
                return this.optnTpFieldSpecified;
            }
            set {
                this.optnTpFieldSpecified = value;
            }
        }

        /// <remarks/>
        public SecuritiesTransactionPrice4Choice__1 StrkPric {
            get {
                return this.strkPricField;
            }
            set {
                this.strkPricField = value;
            }
        }

        /// <remarks/>
        public OptionStyle7Code OptnExrcStyle {
            get {
                return this.optnExrcStyleField;
            }
            set {
                this.optnExrcStyleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptnExrcStyleSpecified {
            get {
                return this.optnExrcStyleFieldSpecified;
            }
            set {
                this.optnExrcStyleFieldSpecified = value;
            }
        }

        /// <remarks/>
        public PhysicalTransferType4Code DlvryTp {
            get {
                return this.dlvryTpField;
            }
            set {
                this.dlvryTpField = value;
            }
        }

        /// <remarks/>
        public AssetClassAttributes1Choice__1 AsstClssSpcfcAttrbts {
            get {
                return this.asstClssSpcfcAttrbtsField;
            }
            set {
                this.asstClssSpcfcAttrbtsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum OptionType2Code {

        /// <remarks/>
        CALL,

        /// <remarks/>
        PUTO,

        /// <remarks/>
        OTHR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum OptionStyle7Code {

        /// <remarks/>
        AMER,

        /// <remarks/>
        ASIA,

        /// <remarks/>
        BERM,

        /// <remarks/>
        EURO,

        /// <remarks/>
        OTHR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum PhysicalTransferType4Code {

        /// <remarks/>
        PHYS,

        /// <remarks/>
        OPTL,

        /// <remarks/>
        CASH,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class DebtInstrument4 {

        private System.DateTime mtrtyDtField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime MtrtyDt {
            get {
                return this.mtrtyDtField;
            }
            set {
                this.mtrtyDtField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecurityInstrumentDescription11 {

        private string idField;

        private string fullNmField;

        private string clssfctnTpField;

        private string ntnlCcyField;

        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string FullNm {
            get {
                return this.fullNmField;
            }
            set {
                this.fullNmField = value;
            }
        }

        /// <remarks/>
        public string ClssfctnTp {
            get {
                return this.clssfctnTpField;
            }
            set {
                this.clssfctnTpField = value;
            }
        }

        /// <remarks/>
        public string NtnlCcy {
            get {
                return this.ntnlCcyField;
            }
            set {
                this.ntnlCcyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecurityInstrumentDescription13__1 {

        private SecurityInstrumentDescription11 finInstrmGnlAttrbtsField;

        private DebtInstrument4 debtInstrmAttrbtsField;

        private DerivativeInstrument6__1 derivInstrmAttrbtsField;

        /// <remarks/>
        public SecurityInstrumentDescription11 FinInstrmGnlAttrbts {
            get {
                return this.finInstrmGnlAttrbtsField;
            }
            set {
                this.finInstrmGnlAttrbtsField = value;
            }
        }

        /// <remarks/>
        public DebtInstrument4 DebtInstrmAttrbts {
            get {
                return this.debtInstrmAttrbtsField;
            }
            set {
                this.debtInstrmAttrbtsField = value;
            }
        }

        /// <remarks/>
        public DerivativeInstrument6__1 DerivInstrmAttrbts {
            get {
                return this.derivInstrmAttrbtsField;
            }
            set {
                this.derivInstrmAttrbtsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class FinancialInstrumentAttributes3Choice__1 {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Id", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Othr", typeof(SecurityInstrumentDescription13__1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class ActiveOrHistoricCurrencyAndAmount {

        private string ccyField;

        private decimal valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class AmountAndDirection53 {

        private ActiveOrHistoricCurrencyAndAmount amtField;

        private bool sgnField;

        private bool sgnFieldSpecified;

        /// <remarks/>
        public ActiveOrHistoricCurrencyAndAmount Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }

        /// <remarks/>
        public bool Sgn {
            get {
                return this.sgnField;
            }
            set {
                this.sgnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SgnSpecified {
            get {
                return this.sgnFieldSpecified;
            }
            set {
                this.sgnFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransactionPrice1 {

        private PriceStatus1Code pdgField;

        private string ccyField;

        /// <remarks/>
        public PriceStatus1Code Pdg {
            get {
                return this.pdgField;
            }
            set {
                this.pdgField = value;
            }
        }

        /// <remarks/>
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum PriceStatus1Code {

        /// <remarks/>
        PNDG,

        /// <remarks/>
        NOAP,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransactionPrice4Choice {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoPric", typeof(SecuritiesTransactionPrice1))]
        [System.Xml.Serialization.XmlElementAttribute("Pric", typeof(SecuritiesTransactionPrice2Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class ESMA_PositiveExcludingZeroMax18 {

        private string ccyField;

        private decimal valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class FinancialInstrumentQuantity25Choice__1 {

        private object itemField;

        private ItemChoiceType2 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MntryVal", typeof(ESMA_PositiveExcludingZeroMax18))]
        [System.Xml.Serialization.XmlElementAttribute("NmnlVal", typeof(ESMA_PositiveExcludingZeroMax18))]
        [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType2 {

        /// <remarks/>
        MntryVal,

        /// <remarks/>
        NmnlVal,

        /// <remarks/>
        Unit,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransaction1__1 {

        private System.DateTime tradDtField;

        private RegulatoryTradingCapacity1Code tradgCpctyField;

        private FinancialInstrumentQuantity25Choice__1 qtyField;

        private VariationType1Code derivNtnlChngField;

        private bool derivNtnlChngFieldSpecified;

        private SecuritiesTransactionPrice4Choice pricField;

        private decimal netAmtField;

        private bool netAmtFieldSpecified;

        private string tradVnField;

        private string ctryOfBrnchField;

        private AmountAndDirection53 upFrntPmtField;

        private string tradPlcMtchgIdField;

        private string cmplxTradCmpntIdField;

        /// <remarks/>
        public System.DateTime TradDt {
            get {
                return this.tradDtField;
            }
            set {
                this.tradDtField = value;
            }
        }

        /// <remarks/>
        public RegulatoryTradingCapacity1Code TradgCpcty {
            get {
                return this.tradgCpctyField;
            }
            set {
                this.tradgCpctyField = value;
            }
        }

        /// <remarks/>
        public FinancialInstrumentQuantity25Choice__1 Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }

        /// <remarks/>
        public VariationType1Code DerivNtnlChng {
            get {
                return this.derivNtnlChngField;
            }
            set {
                this.derivNtnlChngField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DerivNtnlChngSpecified {
            get {
                return this.derivNtnlChngFieldSpecified;
            }
            set {
                this.derivNtnlChngFieldSpecified = value;
            }
        }

        /// <remarks/>
        public SecuritiesTransactionPrice4Choice Pric {
            get {
                return this.pricField;
            }
            set {
                this.pricField = value;
            }
        }

        /// <remarks/>
        public decimal NetAmt {
            get {
                return this.netAmtField;
            }
            set {
                this.netAmtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NetAmtSpecified {
            get {
                return this.netAmtFieldSpecified;
            }
            set {
                this.netAmtFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string TradVn {
            get {
                return this.tradVnField;
            }
            set {
                this.tradVnField = value;
            }
        }

        /// <remarks/>
        public string CtryOfBrnch {
            get {
                return this.ctryOfBrnchField;
            }
            set {
                this.ctryOfBrnchField = value;
            }
        }

        /// <remarks/>
        public AmountAndDirection53 UpFrntPmt {
            get {
                return this.upFrntPmtField;
            }
            set {
                this.upFrntPmtField = value;
            }
        }

        /// <remarks/>
        public string TradPlcMtchgId {
            get {
                return this.tradPlcMtchgIdField;
            }
            set {
                this.tradPlcMtchgIdField = value;
            }
        }

        /// <remarks/>
        public string CmplxTradCmpntId {
            get {
                return this.cmplxTradCmpntIdField;
            }
            set {
                this.cmplxTradCmpntIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum RegulatoryTradingCapacity1Code {

        /// <remarks/>
        MTCH,

        /// <remarks/>
        DEAL,

        /// <remarks/>
        AOTC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum VariationType1Code {

        /// <remarks/>
        DECR,

        /// <remarks/>
        INCR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransactionTransmission2 {

        private bool trnsmssnIndField;

        private string trnsmttgBuyrField;

        private string trnsmttgSellrField;

        /// <remarks/>
        public bool TrnsmssnInd {
            get {
                return this.trnsmssnIndField;
            }
            set {
                this.trnsmssnIndField = value;
            }
        }

        /// <remarks/>
        public string TrnsmttgBuyr {
            get {
                return this.trnsmttgBuyrField;
            }
            set {
                this.trnsmttgBuyrField = value;
            }
        }

        /// <remarks/>
        public string TrnsmttgSellr {
            get {
                return this.trnsmttgSellrField;
            }
            set {
                this.trnsmttgSellrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class PersonOrOrganisation2Choice__1 {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prsn", typeof(PersonIdentification10__1))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class PersonIdentification10__1 {

        private string frstNmField;

        private string nmField;

        private System.DateTime birthDtField;

        private GenericPersonIdentification1__1 othrField;

        /// <remarks/>
        public string FrstNm {
            get {
                return this.frstNmField;
            }
            set {
                this.frstNmField = value;
            }
        }

        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDt {
            get {
                return this.birthDtField;
            }
            set {
                this.birthDtField = value;
            }
        }

        /// <remarks/>
        public GenericPersonIdentification1__1 Othr {
            get {
                return this.othrField;
            }
            set {
                this.othrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class PersonOrOrganisation1Choice__1 {

        private object itemField;

        private ItemChoiceType1 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Intl", typeof(InternalPartyRole1Code))]
        [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("MIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prsn", typeof(PersonIdentification10__1))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public enum InternalPartyRole1Code {

        /// <remarks/>
        INTC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01", IncludeInSchema=false)]
    public enum ItemChoiceType1 {

        /// <remarks/>
        Intl,

        /// <remarks/>
        LEI,

        /// <remarks/>
        MIC,

        /// <remarks/>
        Prsn,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class PartyIdentification76__1 {

        private PersonOrOrganisation1Choice__1 idField;

        private string ctryOfBrnchField;

        /// <remarks/>
        public PersonOrOrganisation1Choice__1 Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string CtryOfBrnch {
            get {
                return this.ctryOfBrnchField;
            }
            set {
                this.ctryOfBrnchField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class PartyIdentification79__1 {

        private PartyIdentification76__1[] acctOwnrField;

        private PersonOrOrganisation2Choice__1[] dcsnMakrField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AcctOwnr")]
        public PartyIdentification76__1[] AcctOwnr {
            get {
                return this.acctOwnrField;
            }
            set {
                this.acctOwnrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DcsnMakr")]
        public PersonOrOrganisation2Choice__1[] DcsnMakr {
            get {
                return this.dcsnMakrField;
            }
            set {
                this.dcsnMakrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.016.001.01")]
    public partial class SecuritiesTransactionReport4__1 {

        private string txIdField;

        private string exctgPtyField;

        private bool invstmtPtyIndField;

        private string submitgPtyField;

        private PartyIdentification79__1 buyrField;

        private PartyIdentification79__1 sellrField;

        private SecuritiesTransactionTransmission2 ordrTrnsmssnField;

        private SecuritiesTransaction1__1 txField;

        private FinancialInstrumentAttributes3Choice__1 finInstrmField;

        private InvestmentParty1Choice__1 invstmtDcsnPrsnField;

        private ExecutingParty1Choice__1 exctgPrsnField;

        private SecuritiesTransactionIndicator2__1 addtlAttrbtsField;

        private RecordTechnicalData1__1 techAttrbtsField;

        /// <remarks/>
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
            }
        }

        /// <remarks/>
        public string ExctgPty {
            get {
                return this.exctgPtyField;
            }
            set {
                this.exctgPtyField = value;
            }
        }

        /// <remarks/>
        public bool InvstmtPtyInd {
            get {
                return this.invstmtPtyIndField;
            }
            set {
                this.invstmtPtyIndField = value;
            }
        }

        /// <remarks/>
        public string SubmitgPty {
            get {
                return this.submitgPtyField;
            }
            set {
                this.submitgPtyField = value;
            }
        }

        /// <remarks/>
        public PartyIdentification79__1 Buyr {
            get {
                return this.buyrField;
            }
            set {
                this.buyrField = value;
            }
        }

        /// <remarks/>
        public PartyIdentification79__1 Sellr {
            get {
                return this.sellrField;
            }
            set {
                this.sellrField = value;
            }
        }

        /// <remarks/>
        public SecuritiesTransactionTransmission2 OrdrTrnsmssn {
            get {
                return this.ordrTrnsmssnField;
            }
            set {
                this.ordrTrnsmssnField = value;
            }
        }

        /// <remarks/>
        public SecuritiesTransaction1__1 Tx {
            get {
                return this.txField;
            }
            set {
                this.txField = value;
            }
        }

        /// <remarks/>
        public FinancialInstrumentAttributes3Choice__1 FinInstrm {
            get {
                return this.finInstrmField;
            }
            set {
                this.finInstrmField = value;
            }
        }

        /// <remarks/>
        public InvestmentParty1Choice__1 InvstmtDcsnPrsn {
            get {
                return this.invstmtDcsnPrsnField;
            }
            set {
                this.invstmtDcsnPrsnField = value;
            }
        }

        /// <remarks/>
        public ExecutingParty1Choice__1 ExctgPrsn {
            get {
                return this.exctgPrsnField;
            }
            set {
                this.exctgPrsnField = value;
            }
        }

        /// <remarks/>
        public SecuritiesTransactionIndicator2__1 AddtlAttrbts {
            get {
                return this.addtlAttrbtsField;
            }
            set {
                this.addtlAttrbtsField = value;
            }
        }

        /// <remarks/>
        public RecordTechnicalData1__1 TechAttrbts {
            get {
                return this.techAttrbtsField;
            }
            set {
                this.techAttrbtsField = value;
            }
        }
    }
}
