//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.6.1055.0.
//
namespace BeanSpitter.Tests.XmlSchemaReaderTests.ClassesFromXsds.Mifid.Headers {
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:head.003.001.01")]
    [System.Xml.Serialization.XmlRootAttribute("BizData", Namespace="urn:iso:std:iso:20022:tech:xsd:head.003.001.01", IsNullable=false)]
    public partial class BusinessDataHeaderV01 {

        private System.Xml.XmlElement hdrField;

        private System.Xml.XmlElement pyldField;

        /// <remarks/>
        public System.Xml.XmlElement Hdr {
            get {
                return this.hdrField;
            }
            set {
                this.hdrField = value;
            }
        }

        /// <remarks/>
        public System.Xml.XmlElement Pyld {
            get {
                return this.pyldField;
            }
            set {
                this.pyldField = value;
            }
        }
    }
}
